# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.household import Household

class TestHousehold(unittest.TestCase):
    """Household unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Household:
        """Test Household
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Household`
        """
        model = Household()
        if include_optional:
            return Household(
                cash_on_hand = 0,
                living_renting = True,
                housing_rental_type = '',
                living_owner = True,
                living_staying_with_friend = True,
                living_hotel = True,
                living_shelter = True,
                living_prefer_not_to_say = True
            )
        else:
            return Household(
        )
        """

    def testHousehold(self):
        """Test Household"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
