# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.confirm_password_request import ConfirmPasswordRequest

class TestConfirmPasswordRequest(unittest.TestCase):
    """ConfirmPasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfirmPasswordRequest:
        """Test ConfirmPasswordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfirmPasswordRequest`
        """
        model = ConfirmPasswordRequest()
        if include_optional:
            return ConfirmPasswordRequest(
                username = '',
                new_password = '',
                verification_code = ''
            )
        else:
            return ConfirmPasswordRequest(
        )
        """

    def testConfirmPasswordRequest(self):
        """Test ConfirmPasswordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
