# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_authenticate(self) -> None:
        """Test case for authenticate

        """
        pass

    def test_confirm_password(self) -> None:
        """Test case for confirm_password

        """
        pass

    def test_forgot_password(self) -> None:
        """Test case for forgot_password

        """
        pass

    def test_get_bulk_eligibility_programs(self) -> None:
        """Test case for get_bulk_eligibility_programs

        """
        pass

    def test_get_eligible_programs(self) -> None:
        """Test case for get_eligible_programs

        """
        pass


if __name__ == '__main__':
    unittest.main()
