# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.person import Person

class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Person:
        """Test Person
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Person`
        """
        model = Person()
        if include_optional:
            return Person(
                age = 56,
                student = True,
                student_fulltime = True,
                pregnant = True,
                unemployed = True,
                unemployed_worked_last18_months = True,
                blind = True,
                disabled = True,
                veteran = True,
                benefits_medicaid = True,
                benefits_medicaid_disability = True,
                household_member_type = 'HeadOfHousehold',
                living_owner_on_deed = True,
                living_rental_on_lease = True,
                incomes = [
                    openapi_client.models.income.Income(
                        amount = 1.337, 
                        type = 'Wages', 
                        frequency = 'Weekly', )
                    ],
                expenses = [
                    openapi_client.models.expense.Expense(
                        amount = 1.337, 
                        type = 'ChildCare', 
                        frequency = 'Weekly', )
                    ]
            )
        else:
            return Person(
        )
        """

    def testPerson(self):
        """Test Person"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
