# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_eligible_programs200_response import GetEligiblePrograms200Response

class TestGetEligiblePrograms200Response(unittest.TestCase):
    """GetEligiblePrograms200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEligiblePrograms200Response:
        """Test GetEligiblePrograms200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEligiblePrograms200Response`
        """
        model = GetEligiblePrograms200Response()
        if include_optional:
            return GetEligiblePrograms200Response(
                type = 'SUCCESS',
                eligibile_programs = [
                    openapi_client.models.eligible_program.EligibleProgram(
                        code = '', 
                        name = '', )
                    ]
            )
        else:
            return GetEligiblePrograms200Response(
        )
        """

    def testGetEligiblePrograms200Response(self):
        """Test GetEligiblePrograms200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
