# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.forgot_password200_response import ForgotPassword200Response

class TestForgotPassword200Response(unittest.TestCase):
    """ForgotPassword200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForgotPassword200Response:
        """Test ForgotPassword200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForgotPassword200Response`
        """
        model = ForgotPassword200Response()
        if include_optional:
            return ForgotPassword200Response(
                type = 'SUCCESS'
            )
        else:
            return ForgotPassword200Response(
        )
        """

    def testForgotPassword200Response(self):
        """Test ForgotPassword200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
