# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.authenticate400_response import Authenticate400Response

class TestAuthenticate400Response(unittest.TestCase):
    """Authenticate400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Authenticate400Response:
        """Test Authenticate400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Authenticate400Response`
        """
        model = Authenticate400Response()
        if include_optional:
            return Authenticate400Response(
                type = '',
                errors = [
                    openapi_client.models.error_model.ErrorModel(
                        message = '', 
                        more_info = '', 
                        code = 'any.required', 
                        element_path = '', )
                    ]
            )
        else:
            return Authenticate400Response(
        )
        """

    def testAuthenticate400Response(self):
        """Test Authenticate400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
