# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Household(BaseModel):
    """
    Household
    """ # noqa: E501
    cash_on_hand: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="How much does your whole household has right now in; cash on hand, checking or saving accounts, stocks, bonds or mutual funds.", alias="cashOnHand")
    living_renting: Optional[StrictBool] = Field(default=False, description="Renting the current living situation.", alias="livingRenting")
    housing_rental_type: Optional[StrictStr] = Field(default='', description="The type of rental, if renting.", alias="housingRentalType")
    living_owner: Optional[StrictBool] = Field(default=False, description="A household member owns the home or apartment.", alias="livingOwner")
    living_staying_with_friend: Optional[StrictBool] = Field(default=False, description="Staying with a friend", alias="livingStayingWithFriend")
    living_hotel: Optional[StrictBool] = Field(default=False, description="In a hotel.", alias="livingHotel")
    living_shelter: Optional[StrictBool] = Field(default=False, description="In a shelter or homeless.", alias="livingShelter")
    living_prefer_not_to_say: Optional[StrictBool] = Field(default=False, description="Preference to not disclose housing.", alias="livingPreferNotToSay")
    __properties: ClassVar[List[str]] = ["cashOnHand", "livingRenting", "housingRentalType", "livingOwner", "livingStayingWithFriend", "livingHotel", "livingShelter", "livingPreferNotToSay"]

    @field_validator('housing_rental_type')
    def housing_rental_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'MarketRate', 'RentControlled', 'FamilyHome', 'Condo', 'NYCHA', 'RentRegulatedHotel', 'Section213', 'LimitedDividendDevelopment', 'MitchellLama', 'RedevelopmentCompany', 'HDFC']):
            raise ValueError("must be one of enum values ('', 'MarketRate', 'RentControlled', 'FamilyHome', 'Condo', 'NYCHA', 'RentRegulatedHotel', 'Section213', 'LimitedDividendDevelopment', 'MitchellLama', 'RedevelopmentCompany', 'HDFC')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Household from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Household from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cashOnHand": obj.get("cashOnHand"),
            "livingRenting": obj.get("livingRenting") if obj.get("livingRenting") is not None else False,
            "housingRentalType": obj.get("housingRentalType") if obj.get("housingRentalType") is not None else '',
            "livingOwner": obj.get("livingOwner") if obj.get("livingOwner") is not None else False,
            "livingStayingWithFriend": obj.get("livingStayingWithFriend") if obj.get("livingStayingWithFriend") is not None else False,
            "livingHotel": obj.get("livingHotel") if obj.get("livingHotel") is not None else False,
            "livingShelter": obj.get("livingShelter") if obj.get("livingShelter") is not None else False,
            "livingPreferNotToSay": obj.get("livingPreferNotToSay") if obj.get("livingPreferNotToSay") is not None else False
        })
        return _obj


