# coding: utf-8

"""
    NYC City-Funded Social Service Contracts - Programs(Filters)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.expense import Expense
from openapi_client.models.income import Income
from typing import Optional, Set
from typing_extensions import Self

class Person(BaseModel):
    """
    Person
    """ # noqa: E501
    age: Optional[StrictInt] = Field(default=None, description="The age of the person.")
    student: Optional[StrictBool] = Field(default=None, description="Whether the person is a student or not.")
    student_fulltime: Optional[StrictBool] = Field(default=None, description="Whether the person is a full-time student or not.", alias="studentFulltime")
    pregnant: Optional[StrictBool] = Field(default=None, description="Whether the person is pregnant or not.")
    unemployed: Optional[StrictBool] = Field(default=None, description="Whether the person is employed or not.")
    unemployed_worked_last18_months: Optional[StrictBool] = Field(default=None, description="Whether the person is unemployed and worked within the last 18 months.", alias="unemployedWorkedLast18Months")
    blind: Optional[StrictBool] = Field(default=None, description="Whether the person is blind or not.")
    disabled: Optional[StrictBool] = Field(default=None, description="Whether the person has disabilities or not.")
    veteran: Optional[StrictBool] = Field(default=None, description="Whether the person is a veteran or not")
    benefits_medicaid: Optional[StrictBool] = Field(default=None, description="Whether the person receives Medicaid benefits or not.", alias="benefitsMedicaid")
    benefits_medicaid_disability: Optional[StrictBool] = Field(default=None, description="Whether the person receives disability-related Medicaid benefits or not", alias="benefitsMedicaidDisability")
    household_member_type: Optional[StrictStr] = Field(default='', description="What is this person's relation to the household?", alias="householdMemberType")
    living_owner_on_deed: Optional[StrictBool] = Field(default=None, description="If the household owns the home is the person the owner or on the deed.", alias="livingOwnerOnDeed")
    living_rental_on_lease: Optional[StrictBool] = Field(default=None, description="If the household rental is renting, whether the person on the lease or not.", alias="livingRentalOnLease")
    incomes: Optional[List[Income]] = Field(default=None, description="A collection of one or more income objects.")
    expenses: Optional[List[Expense]] = Field(default=None, description="Collection of one or more expense objects")
    __properties: ClassVar[List[str]] = ["age", "student", "studentFulltime", "pregnant", "unemployed", "unemployedWorkedLast18Months", "blind", "disabled", "veteran", "benefitsMedicaid", "benefitsMedicaidDisability", "householdMemberType", "livingOwnerOnDeed", "livingRentalOnLease", "incomes", "expenses"]

    @field_validator('household_member_type')
    def household_member_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['HeadOfHousehold', 'Child', 'FosterChild', 'StepChild', 'Grandchild', 'Spouse', 'Parent', 'FosterParent', 'StepParent', 'Grandparent', 'SisterBrother', 'StepSisterStepBrother', 'BoyfriendGirlfriend', 'DomesticPartner', 'Unrelated', '']):
            raise ValueError("must be one of enum values ('HeadOfHousehold', 'Child', 'FosterChild', 'StepChild', 'Grandchild', 'Spouse', 'Parent', 'FosterParent', 'StepParent', 'Grandparent', 'SisterBrother', 'StepSisterStepBrother', 'BoyfriendGirlfriend', 'DomesticPartner', 'Unrelated', '')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Person from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in incomes (list)
        _items = []
        if self.incomes:
            for _item_incomes in self.incomes:
                if _item_incomes:
                    _items.append(_item_incomes.to_dict())
            _dict['incomes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in expenses (list)
        _items = []
        if self.expenses:
            for _item_expenses in self.expenses:
                if _item_expenses:
                    _items.append(_item_expenses.to_dict())
            _dict['expenses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Person from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age": obj.get("age"),
            "student": obj.get("student"),
            "studentFulltime": obj.get("studentFulltime"),
            "pregnant": obj.get("pregnant"),
            "unemployed": obj.get("unemployed"),
            "unemployedWorkedLast18Months": obj.get("unemployedWorkedLast18Months"),
            "blind": obj.get("blind"),
            "disabled": obj.get("disabled"),
            "veteran": obj.get("veteran"),
            "benefitsMedicaid": obj.get("benefitsMedicaid"),
            "benefitsMedicaidDisability": obj.get("benefitsMedicaidDisability"),
            "householdMemberType": obj.get("householdMemberType") if obj.get("householdMemberType") is not None else '',
            "livingOwnerOnDeed": obj.get("livingOwnerOnDeed"),
            "livingRentalOnLease": obj.get("livingRentalOnLease"),
            "incomes": [Income.from_dict(_item) for _item in obj["incomes"]] if obj.get("incomes") is not None else None,
            "expenses": [Expense.from_dict(_item) for _item in obj["expenses"]] if obj.get("expenses") is not None else None
        })
        return _obj


